name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
  
  deploy:
   runs-on: ubuntu-latest
   environment:
    name: staging
    url: https://webapp-deploytest-1-staging.azurewebsites.net
   needs: build
   steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
       name: webapp
